README.md, software/core/NetworkMonitor/include/NetworkMonitor.hpp
Created the initial header file for the Network Manager class.
=> Initial NetworkMonitor Class

software/core/include/DataProcessor.hpp, software/core/src/DataProcessor.cpp
Add implementation and definition for the abstract data processor class.
Make a correction in the DataProcessor.cpp file
Add a correction to the intializatio of the constructor of the class.
Make final edits before review
Removed process() from cpp file
Make a correction in the DataProcessor.cpp file
Add a correction to the intializatio of the constructor of the class.
=> Create Data Processor class

software/core/include/State.hpp, software/core/include/state_enum.hpp
Create States Enum
- Created to replace PR#9
=> Controls state class

software/core/python/src/control-panel/ControlPanel_MainWindow.py, software/core/python/src/control-panel/Layout.py
Created the layout class which returns a horizontal or vertical layout depending on the string you pass it. Also created the mainWindow class, which allows you to create a new window, and create tabs that contain widgets.
=> Infrastructures layout

README.md, software/core/include/Channel.hpp, software/core/src/Channel.cpp
- Channel class implementation complete
- get and publish functions fixed
=> Communications channel

software/core/python/src/control-panel/progress_bar.py
Added a label under the progressbar that displays the min and max values
=> add label displaying min and max values of the progress bar

software/core/python/src/control-panel/main.py, software/core/python/src/control-panel/table.py, software/core/python/src/control-panel/window.py
Adding ability to define header titles for the table. Done by passing in two Lists one for the columns and one for the rows. Must have string for each column/row or exception is raised.
=> Infrastructures table headers

software/core/Infrastructure/backend/Classes/battery-sensor.js, software/core/Infrastructure/backend/Classes/position-sensor.js, software/core/Infrastructure/backend/Classes/sensor.js, software/core/Infrastructure/backend/Classes/speed-sensor.js, software/core/Infrastructure/backend/Classes/temp-sensor.js
-Abstract sensor class
-Speed 
-Temp
-Battery 
-Location
=> Added sensor classes

software/core/Infrastructure/backend/Classes/battery-sensor.js, software/core/Infrastructure/backend/Classes/position-sensor.js, software/core/Infrastructure/backend/Classes/sensor.js, software/core/Infrastructure/backend/Classes/speed-sensor.js, software/core/Infrastructure/backend/Classes/temp-sensor.js, software/core/Infrastructure/backend/Digester/index.js, software/core/Infrastructure/backend/Digester/test.json, software/core/Infrastructure/backend/package.json
Digester function that takes in a json and return an array of sensors objects
=> Digester implementation

software/core/Infrastructure/backend/Classes/battery-sensor.js, software/core/Infrastructure/backend/Classes/position-sensor.js, software/core/Infrastructure/backend/Classes/sensor.js, software/core/Infrastructure/backend/Classes/speed-sensor.js, software/core/Infrastructure/backend/Classes/temp-sensor.js, software/core/Infrastructure/backend/Digester/index.js, software/core/Infrastructure/backend/Digester/test.json, software/core/Infrastructure/backend/Encapsulate/index.js, software/core/Infrastructure/backend/Encapsulate/test.json, software/core/Infrastructure/backend/constant/classes.js, software/core/Infrastructure/backend/package.json
Created the encapsulation function that takes in the digested sensor array and return an object in the form:
{
"SPEED": [ obj ],
"TEMPERATURE" : [obj, obj],
"BATTERY" : [obj]
}
=> Encapsulation function 

software/core/Infrastructure/AngularFrontend/src/app/components/websocket/websocket.component.ts, software/core/Infrastructure/AngularFrontend/src/app/services/data-stream.service.spec.ts, software/core/Infrastructure/AngularFrontend/src/app/services/data-stream.service.ts
Created an ng service module in app/services/data-stream.service.ts that stores the global state coming from the WebSocket module. Any components can subscribe to the service to listen to changes when the global state is updated.
=> Data stream service

software/core/Infrastructure/AngularFrontend/src/app/app.component.html, software/core/Infrastructure/AngularFrontend/src/app/app.module.ts, software/core/Infrastructure/AngularFrontend/src/app/components/layout/layout.component.css, software/core/Infrastructure/AngularFrontend/src/app/components/layout/layout.component.html, software/core/Infrastructure/AngularFrontend/src/app/components/layout/layout.component.spec.ts, software/core/Infrastructure/AngularFrontend/src/app/components/layout/layout.component.ts
=> dashboard layout

software/core/Infrastructure/backend/README.md, software/core/Infrastructure/db/README.md, software/core/Infrastructure/db/pod1models.js, software/core/Infrastructure/scripts/.gitignore, software/core/Infrastructure/scripts/package-lock.json, software/core/Infrastructure/scripts/package.json, software/core/Infrastructure/scripts/route.rest, software/core/Infrastructure/scripts/routes/pod1.js, software/core/Infrastructure/scripts/server.js
- created a README file for MongoDB installation on mac, windows, and Linux
- utilized mongoose to create a basic schema for pod1
- created a README file for documenting mongoose schema
=> implemented mongoose schema for pod1

software/core/Infrastructure/AngularFrontend/src/app/app-routing.module.ts, software/core/Infrastructure/AngularFrontend/src/app/app.component.html, software/core/Infrastructure/AngularFrontend/src/app/app.module.ts, software/core/Infrastructure/AngularFrontend/src/app/components/dashboard/position/position.component.html, software/core/Infrastructure/AngularFrontend/src/app/components/dashboard/position/position.component.ts, software/core/Infrastructure/AngularFrontend/src/app/components/dashboard/switch/switch.component.html, software/core/Infrastructure/AngularFrontend/src/app/components/logs/logs.component.css, software/core/Infrastructure/AngularFrontend/src/app/components/logs/logs.component.html, software/core/Infrastructure/AngularFrontend/src/app/components/logs/logs.component.spec.ts, software/core/Infrastructure/AngularFrontend/src/app/components/logs/logs.component.ts, software/core/Infrastructure/AngularFrontend/src/styles.css
- Added log page
- Used routing to switch between pages
- Minor change to progress bar
=> Infrastructure dev/s18/#kt0jd9

software/core/Infrastructure/backend/Encapsulate/index.js, software/core/Infrastructure/backend/index.js, software/core/Infrastructure/c++/socket.cpp
Timestamp Added for encapsulation. C++ files modified to match needs for nodejs Websockets
=> Timestamp Added

software/core/Infrastructure/AngularFrontend/src/app/app.component.spec.ts, software/core/Infrastructure/AngularFrontend/src/app/app.component.ts, software/core/Infrastructure/AngularFrontend/src/app/components/icons/battery/battery.component.spec.ts, software/core/Infrastructure/AngularFrontend/src/app/components/widgets/gauge-graph/gauge-graph.component.spec.ts, software/core/Infrastructure/AngularFrontend/src/app/components/widgets/gauge-graph/gauge-graph.component.ts, software/core/Infrastructure/AngularFrontend/src/app/components/widgets/gauge/gauge.component.spec.ts, software/core/Infrastructure/AngularFrontend/src/app/components/widgets/gauge/gauge.component.ts, software/core/Infrastructure/AngularFrontend/src/app/components/widgets/graph/graph.component.spec.ts, software/core/Infrastructure/AngularFrontend/src/app/components/widgets/graph/graph.component.ts
Unit tests for gauge/graph components
=> Infrastructure dev/s3/#n756k3

software/core/Infrastructure/AngularFrontend/src/app/components/dashboard/battery/battery.component.ts, software/core/Infrastructure/AngularFrontend/src/app/components/widgets/gauge-graph/gauge-graph.component.spec.ts, software/core/Infrastructure/AngularFrontend/src/app/components/widgets/gauge-graph/gauge-graph.component.ts
- Minor changes to alleviate all front-end unit test errors.
=> Minor debugging changes to remove all errors in front end unit tests

software/core/Infrastructure/backend/index.js, software/core/Infrastructure/backend/validator/commonErrors.json, software/core/Infrastructure/backend/validator/test.json, software/core/Infrastructure/backend/validator/validate-old.js, software/core/Infrastructure/backend/validator/validate.js
Created a new branch with the validation module to get around the merge conflicts from the previous pull request
=> new branch with validation module

software/core/Infrastructure/AngularFrontend/src/app/components/sensor-group/sensor-group.component.html, software/core/Infrastructure/AngularFrontend/src/app/components/sensor-group/sensor-group.component.spec.ts, software/core/Infrastructure/AngularFrontend/src/app/components/sensor-group/sensor-group.component.ts, software/core/Infrastructure/AngularFrontend/src/app/components/sensors/sensors.component.html, software/core/Infrastructure/AngularFrontend/src/app/components/sensors/sensors.component.ts
- Now easier to input data from SensorsComponent
- Add unit tests for sensor items
=> Updated pod sensor status

software/core/Infrastructure/backend/Classes/brake-sensor.js, software/core/Infrastructure/backend/Digester/README.md, software/core/Infrastructure/backend/Digester/index.js, software/core/Infrastructure/backend/Digester/test.json, software/core/Infrastructure/backend/Encapsulate/index.js, software/core/Infrastructure/backend/index.js, software/core/Infrastructure/backend/test.json
Tested the Encapsulator and Digester. Made crash reports for the Digester module.
=> Infrastructure dev/s6/#k0x7kk

software/core/Infrastructure/backend/Digester/index.js
This PR contains:
- fix for the digester
=> Bug fix for digestor

software/core/Infrastructure/README.md, software/core/Infrastructure/UTHT/electronSrc/controller/controller.js, software/core/Infrastructure/UTHT/src/app/app-routing.module.ts, software/core/Infrastructure/UTHT/src/app/app.module.ts, software/core/Infrastructure/UTHT/src/app/components/controls/controls.component.css, software/core/Infrastructure/UTHT/src/app/components/controls/controls.component.html, software/core/Infrastructure/UTHT/src/app/components/controls/controls.component.ts, software/core/Infrastructure/UTHT/src/app/components/sensors/sensors.component.css, software/core/Infrastructure/UTHT/src/app/components/sensors/sensors.component.html, software/core/Infrastructure/UTHT/src/app/services/websocket.service.ts, software/core/Infrastructure/UTHT/src/index.html, software/core/Infrastructure/c++/socketBoost.cpp
This PR includes:
- Connecting each button with the websocket
- Styling for the button is fixed
- Image for bird eye view is not being shown
=> Button are fixed, styling sheet is being accessed properly
